services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Jenkins URL http://localhost:8080
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home


volumes:
  jenkins_home: